[package]
name = "vesting"
version = "0.0.0"
authors = [ "Skyzox"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.23.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.23.0"